### ISSUE TITLE
WdmmgResponse.budgets の要素に budget item id が含まれていない

### ISSUE THREAD

**Issue by yuukiootaki** [spendingjp/openspending-backend#122]
frontend の mapping.vue で扱っている WdmmgResponse.budgets の要素は実質 Classification. オブジェクトに含まれている id は Classification の id。
budget の id も含める。mappedBudgetItem を作成する API を叩くために budget item id が必要。

**Comment by yuukiootaki** [comment]
ついでに、すでに mappedBudgetItems が存在する要素はその情報も含めて返すようにする。

**Comment by osoken** [comment]
#121 でクエリに `budget_id` を含める必要はなくなりました！
https://github.com/spendingjp/openspending-backend/pull/121/files#diff-3c6f368eab3d0dbae9edfb4c9848c9576ad42c6639ce61575c55887c08a8018cL1481-L1485

**Comment by yuukiootaki** [comment]
作業中

**Comment by yuukiootaki** [comment]
> すでに mappedBudgetItems が存在する要素はその情報も含めて返すようにする。

テストの修正がめんどくさそう

**Comment by yuukiootaki** [comment]
やらなくてもいいので閉じます。
