### ISSUE TITLE
認証機構の作成

### ISSUE THREAD

**Issue by kaizumaki** [spendingjp/openspending-backend#2]
管理画面にログイン機能が必要かどうか。

**Comment by kaizumaki** [comment]
書き込みに認証が必要なので、ログイン画面も必要。

**Comment by takano32** [comment]
Vuetify Admin

https://www.npmjs.com/package/vuetify-admin

Vuetify Admin による認証についての公式ドキュメント

https://www.okami101.io/vuetify-admin/guide/authentication.html


> VA provides 3 configurable auth providers :
> 
> basicAuthProvider : Basic HTTP authentication.
> jwtAuthProvider : JWT for stateless authentication.
> sanctumAuthProvider : Full state cookie authentication which is the recommended way if you use Laravel.

**Comment by takano32** [comment]
ログインのフォームに着手します。

**Comment by osoken** [comment]
token 認証のルートを作成したので、リクエストを `curl` で送るサンプルを載せておきます

```
curl http://localhost:8000/api-token-auth/ -XPOST -H "Content-Type: application/json" -d'{"username":"awesomesuperuser","password":"str0ngP@ssword"}'
```
レスポンスとして、以下が返ってくる
```
{"token":"fdc31...4"}
```
これをヘッダにセットして送信という感じです

```
curl http://localhost:8000/api/v1/classifiaction-systems/ -XPOST -H"Content-Type: application/json" -d'{"name":"まほろ市2103年度予算","slug":"mahoro-city-2103-budget"}' -H"Authorization: Token fdc31...4"
```

**Comment by kaizumaki** [comment]
@osoken ありがとうございます！こちら私のほうで引き取りますね。

**Comment by kaizumaki** [comment]
こちら、tokenの検証ができたのでクローズします。
